services:
  # Neo4j Community Edition - Configuration minimale
  neo4j:
    image: neo4j:5.15-community
    container_name: myreprise_neo4j_simple
    ports:
      - "7474:7474"  # Interface Neo4j Browser
      - "7687:7687"  # Port Bolt pour connexions
    environment:
      - NEO4J_AUTH=neo4j/neo4j123
    volumes:
      - neo4j_data_simple:/data
    networks:
      - myreprise-network
    restart: unless-stopped

volumes:
  neo4j_data_simple:

networks:
  myreprise-network:
    driver: bridge
